---
# tasks file for keepalived
- name: Install Keepalived
  yum: 
    name: "keepalived"
    state: latest

-name: Configure keepalived with the right settings
  template:
  src: keepalived.js
  dest: /etc/keepalived/keepalived.conf
  notify: restart keepalived

